---
- name: Include OS-specific settings
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific settings
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - defaults.yml
