---
- hosts: [debian, ubuntu]

  handlers:
    - name: reload apache
      service:
        name: apache2
        state: reloaded
      listen: "restart web services"

  tasks:
    - name: Paketlisten aktualisieren
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Apache-Paket installieren
      ansible.builtin.apt:
        name: apache2

    - name: Dienst starten und in Bootprozess integrieren
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Minimale Startseite einrichten
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: 0644
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8" />
              <title>Willkommen auf unserer Homepage!</title>
            </head>
            <body>
              <h1>Willkommen auf unserer coolen Homepage</h1>
            </body>
          </html>

    - name: Plugin-config hochladen
      ansible.builtin.copy:
        dest: /etc/apache2/conf-available/redirect.conf
        content: |
          Redirect /go http://docs.ansible.com/
      notify: restart web services

    - name: Config aktivieren
      ansible.builtin.command:
        cmd: a2enconf redirect
        creates: /etc/apache2/conf-enabled/redirect.conf

- hosts: localhost

  tasks:
    - name: Paket curl installieren
      ansible.builtin.apt:
        name: curl
        state: present
