---
- hosts: all
  gather_facts: true

  tasks:
    - name: Platzbedarf der Root-Partition ermitteln
      command: df -h /
      changed_when: false
      register: df_cmd

    - ansible.builtin.debug:
        msg: "{{ df_cmd.stdout_lines }}"

    - ansible.builtin.debug: var=df_cmd

    - ansible.builtin.debug:
        msg: "Command run: {{ df_cmd.cmd | join(' ') }}"


    - ansible.builtin.debug:
        msg: "Dist family: {{ ansible_facts.distribution_file_variety }}"
