---
- hosts: all

  tasks:
    - name: Mit find nichts finden soll Fehler sein
      command: find /etc -name blabla.conf
      changed_when: false
      register: find_cmd
      failed_when: find_cmd.stdout == '' or find_cmd.rc != 0

    - debug: msg={{ find_cmd.stdout }}
