---
- hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: var1
      private: false
      prompt: Bitte einen Wert fuer var1 eingeben
      default: 42

    - name: var2
      private: true
      prompt: Und noch einen fuer var2 (darf niemand sehen)

  tasks:
    - debug:
        msg: "var1 ist {{ var1 }}, var2 is {{ var2 }}"
