---
- hosts: all
  gather_facts: false

  vars_files:
    - vars/setup.yml
    - [ vars/additional.yml, vars/common.yml ]

  tasks:
    - debug:
        msg: "Farbe: {{ farbe }}, Zahl: {{ zahl }}, Material: {{ material }}, Wind: {{ wind }}"
