---
- assert:
    that:
      - apache_admin_pass != None
    fail_msg: Setzen Sie bitte ein Passwort mit apache_admin_pass

- name: Systemspezifische Parameter laden
  include_vars: >
   {{ ansible_distribution | lower | replace(" ", "-") }}.yml

- name: Paketlisten auf Debian-Systemen aktualisieren
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Aapche-Paket installieren
  ansible.builtin.package:
    name: "{{ apache_package_name }}"

- name: Dienst sraten und in Bootprozess integrieren
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: true

- name: Minimale Startseite einrichten
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ apache_document_root }}/index.html"
    mode: 0644

- name: Plugin-Config hochladen
  copy:
    dest: "{{ apache_config_directory }}/redirect.conf"
    content: |
      Redirect /go https://www.google.ch
  notify: reload apache

- name: Config aktivieren (nur auf Debian-System nötig)
  command:
    cmd: a2enconf redirect
    creates: /etc/apache2/conf-enabled/redirect.conf
  when: ansible_os_family == "Debian"
